### ISSUE TITLE
Return file and a setFile function with fileURL

### ISSUE THREAD

**Issue by VitorLuizC** [VitorLuizC/use-object-url#2]

**Comment by mechamobau** [comment]
@VitorLuizC Can you explain more details about what you need?

**Comment by VitorLuizC** [comment]
Sorry, what I mean with this issue is a breaking change. Instead of returning the objectURL, it would return an object with the file/object, the objectURL and a function to update file/object.

Something like:

```js
const { objectURL, object, setObject } = useObjectURL(initialObject);
```

**Comment by mechamobau** [comment]
Right, I'll work on that. The return type of object URL needs to be a Base64 URL?

**Comment by VitorLuizC** [comment]
its the createObjectUrl function.
